<a href="https://colab.research.google.com/github/chandanapatil/Application-of-Python-Programming-in-DA-and-ML/blob/master/Day_3_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 Write a Pandas program to create and display a one-dimensional array using series  containing  event numbers upto 10000

In [ ]:
import pandas as pd
import numpy as np
pd.Series([i for i in range(1,1000) if i%2==0])


0        2
1        4
2        6
3        8
4       10
      ... 
494    990
495    992
496    994
497    996
498    998
Length: 499, dtype: int64

#2 Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 

In [ ]:
l1=pd.Series([i for i in range(1000,2001) if i%5==0])
print("Pandas Series and type")
print(l1)
print("Convert Pandas Series to Python list")
print(l1.tolist())
print(type(l1.tolist()))
print(type(l1))


Pandas Series and type
0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
196    1980
197    1985
198    1990
199    1995
200    2000
Length: 201, dtype: int64
Convert Pandas Series to Python list
[1000, 1005, 1010, 1015, 1020, 1025, 1030, 1035, 1040, 1045, 1050, 1055, 1060, 1065, 1070, 1075, 1080, 1085, 1090, 1095, 1100, 1105, 1110, 1115, 1120, 1125, 1130, 1135, 1140, 1145, 1150, 1155, 1160, 1165, 1170, 1175, 1180, 1185, 1190, 1195, 1200, 1205, 1210, 1215, 1220, 1225, 1230, 1235, 1240, 1245, 1250, 1255, 1260, 1265, 1270, 1275, 1280, 1285, 1290, 1295, 1300, 1305, 1310, 1315, 1320, 1325, 1330, 1335, 1340, 1345, 1350, 1355, 1360, 1365, 1370, 1375, 1380, 1385, 1390, 1395, 1400, 1405, 1410, 1415, 1420, 1425, 1430, 1435, 1440, 1445, 1450, 1455, 1460, 1465, 1470, 1475, 1480, 1485, 1490, 1495, 1500, 1505, 1510, 1515, 1520, 1525, 1530, 1535, 1540, 1545, 1550, 1555, 1560, 1565, 1570, 1575, 1580, 1585, 1590, 1595, 1600, 1605, 1610, 1615, 1620, 1625, 1630, 1635, 1640, 1645, 1

#3 Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
ds1=pd.Series([i for i in range(1,101) if i%2==0])
ds2=pd.Series([i for i in range(1,101) if i%2!=0])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


#4 Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]


In [ ]:
ds1=([i for i in range(1,1000) if i%7==0])
pd1=pd.Series(ds1)
ds2=([i for i in range(1,1000) if i%11==0])
pd2=pd.Series(ds2)
print("Series1:")
print(pd1)
print("Series2:")
print(pd2)
print("Compare the elements of the said Series:")
print("Equals:")
for i in range (len(ds2)):
  print(i," ",pd1[i]==pd2[i])
print("Greater than:")
for i in range(len(ds2)):
  print(i," ",pd1[i]>pd2[i])
print("Less than:")
for i in range(len(ds2)):
  print(i," ",pd1[i]<pd2[i])

#5 Write a Pandas program to convert a NumPy array to a Pandas series. 
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]


In [ ]:
import numpy as np
n1=np.array([i for i in range(10,1001) if i%10==0])
print("Numpy series")
print(n1)
p1= pd.Series(n1)
print("Converted Pandas series:")
print(p1)

Numpy series
[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000]
Converted Pandas series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


#6 Write a Pandas program to convert a given Series to an array.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [ ]:
s1=pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print(s1)
a = np.array(s1.values.tolist())
print (a)

0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


#7 Write a Pandas program to sort a given Series.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [ ]:
s1=pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print(s1)
s2=pd.Series(s1).sort_values()

0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object


#8 Write a Pandas program to create a subsets of a given series based on value and condition.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
value and condtion :  Subset 1 :numbers divisable by 7  Subset 2 : numbers divisable by 5


In [ ]:
import pandas as pd
l1=([i for i in range(0,1001) if i%10==0])
s = pd.Series(l1)
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n=7
n1= s[s%n==0]
print(n1)
n=5
n1 = s[s%n==0]
print(n1)

Original Data Series:
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64

Subset of the above Data Series:
0       0
7      70
14    140
21    210
28    280
35    350
42    420
49    490
56    560
63    630
70    700
77    770
84    840
91    910
98    980
dtype: int64
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64


#9 Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [ ]:
import pandas as pd
l=[]
for val in range(0,1001):
  if val > 1: 
        for n in range(2, val//2 + 2): 
            if (val % n) == 0: 
                break
            else: 
                if n == val//2 + 1: 
                    l.append(val)
s = pd.Series(data = l)
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        3
1        5
2        7
3       11
4       13
      ... 
162    971
163    977
164    983
165    991
166    997
Length: 167, dtype: int64
Mean of the said Data Series:
455.8383233532934
Standard deviation of the said Data Series:
297.0201672063572


#10 Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}


In [ ]:
import pandas as pd
l1=([i for i in range(0,1001) if i%7!=0 and i%2!=0])
p1=pd.Series(l1)
l2=([i for i in range(0,1001) if i%2==0 and i%5!=0])
p2=pd.Series(l2)
l3=([i for i in range(0,1001) if i%2!=0 and i%3!=0])
p3=pd.Series(l3)
print(len(l1),len(l2),len(l3))
for i in range(len(l3)):
  df = pd.DataFrame({'X':p1, 'Y':p2,'Z':p3})
print(df)

429 400 333
       X     Y     Z
0      1   2.0   1.0
1      3   4.0   5.0
2      5   6.0   7.0
3      9   8.0  11.0
4     11  12.0  13.0
..   ...   ...   ...
424  991   NaN   NaN
425  993   NaN   NaN
426  995   NaN   NaN
427  997   NaN   NaN
428  999   NaN   NaN

[429 rows x 3 columns]



#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.


In [2]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Apoorva', 'Bhramari', 'Pavitra', 'Rachana', 'Bhavana', 'Sunil', 'Amit', 'Amrutha', 'Kavana', 'Chandana'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
df1 = df[['name','score','attempts']]
df1.head(10)

First three rows of the data frame:


name  score  attempts
a   Apoorva   12.5         1
b  Bhramari    9.0         3
c   Pavitra   16.5         2
d   Rachana    NaN         3
e   Bhavana    9.0         2
f     Sunil   20.0         3
g      Amit   14.5         1
h   Amrutha    NaN         1
i    Kavana    8.0         2
j  Chandana   19.0         1

#Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).

In [ ]:
import pandas as pd
xyz = pd.read_csv('movie_metadata.csv') 
df = xyz[['language','country','duration']]
print(df.head(10))

  language country  duration
0  English     USA     178.0
1  English     USA     169.0
2  English      UK     148.0
3  English     USA     164.0
4      NaN     NaN       NaN
5  English     USA     132.0
6  English     USA     156.0
7  English     USA     100.0
8  English     USA     141.0
9  English      UK     153.0


#Write a Pandas program to find the mean and standard deviation, maximum and minimum of the data of 50 students Python marks stored in a CSV file called Python_mark.csv( you have to create the file yourself like rollno,mark for 50 records)

In [ ]:
import pandas as pd
df = pd.DataFrame({'roll number':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],'marks':[20,22,23,24,25,26,27,12,13,15,23,24,23,21,12,13,14,15,30,24,25,26,27,28,29,30,22,22,22,22,23,23,23,23,23,23,24,24,24,25,26,26,27,27,27,27,27,26,27,23]})
print(df.mean())
print(df.std())
print(df.min())
print(df.max())

roll number    25.50
marks          23.14
dtype: float64
roll number    14.577380
marks           4.558061
dtype: float64
roll number     1
marks          12
dtype: int64
roll number    50
marks          30
dtype: int64


In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)

Details of the seventh movie:
color                                                                    Color
director_name                                                Christopher Nolan
num_critic_for_reviews                                                     813
duration                                                                   164
director_facebook_likes                                                  22000
actor_3_facebook_likes                                                   23000
actor_2_name                                                    Christian Bale
actor_1_facebook_likes                                                   27000
gross                                                              4.48131e+08
genres                                                         Action|Thriller
actor_1_name                                                         Tom Hardy
movie_title                                             The Dark Knight Rises 
num_voted_users       

#Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields

In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
result = df[['title_year']]
print("Details of title and genres:")
print(result.sort_values('title_year'))

Details of title and genres:
      title_year
4810      1916.0
4958      1920.0
4885      1925.0
2734      1927.0
4812      1929.0
...          ...
4798         NaN
4803         NaN
4819         NaN
4869         NaN
5039         NaN

[5043 rows x 1 columns]


#Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv

In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
# Create a smaller dataframe
small_df = df[['country','language']]
print("DataFrame based on country and language")
print(small_df.sort_values('country'))
print(small_df.sort_values('language'))

DataFrame based on country and language
          country language
4735  Afghanistan     Dari
4450    Argentina  Spanish
4666    Argentina  Spanish
4415    Argentina  Spanish
4000    Argentina  Spanish
...           ...      ...
4             NaN      NaN
279           NaN      NaN
2370          NaN  English
3397          NaN  English
4021          NaN  English

[5043 rows x 2 columns]
        country    language
5031    English           8
3504  Australia  Aboriginal
377          UK  Aboriginal
4393     France      Arabic
4580    Germany      Arabic
...         ...         ...
4409        USA         NaN
4630        USA         NaN
4810        USA         NaN
4885        USA         NaN
4958        USA         NaN

[5043 rows x 2 columns]


#Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [ ]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 
y = np.array(x[1:3])
y

Original Array:
[[0.19205275 0.33385891 0.07279445 0.64084907]
 [0.39086067 0.67571598 0.73518891 0.55025306]
 [0.51726018 0.08958415 0.97470235 0.72540911]
 [0.91067927 0.11467734 0.70827591 0.67573534]]


array([[0.39086067, 0.67571598, 0.73518891, 0.55025306],
       [0.51726018, 0.08958415, 0.97470235, 0.72540911]])

#Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[1.83598116e-01 9.98110152e-01 5.31002148e-01 8.93913336e-01
  7.57961433e-02 5.95543719e-01 9.81619748e-01 3.81743285e-01
  4.87909348e-01 8.79942719e-01]
 [9.88332634e-01 9.57852587e-01 8.46032021e-01 3.43867962e-01
  4.05887522e-01 8.66276107e-01 3.27136885e-01 4.73760275e-01
  4.28060901e-01 3.00481112e-01]
 [7.39929300e-01 1.12839187e-01 7.36913183e-01 6.04429209e-01
  3.83655838e-01 3.92232323e-01 3.01667140e-01 4.64401881e-01
  3.19608460e-01 3.77742630e-01]
 [6.69548884e-01 2.28362324e-01 2.36006213e-01 6.62824716e-01
  4.31036781e-02 1.42393055e-01 6.17605211e-01 2.17918685e-01
  3.62294254e-01 5.26271071e-01]
 [8.76316183e-01 3.45425022e-01 6.03602635e-01 9.71534693e-01
  4.60853278e-01 1.76781558e-01 7.54469067e-01 2.23893171e-01
  8.65962721e-01 8.53462429e-01]
 [6.29091839e-04 8.90372283e-01 7.04421582e-02 7.16269646e-01
  3.23753347e-01 3.56200822e-01 6.00004715e-01 9.51987017e-03
  1.98112649e-01 6.76858209e-01]
 [8.95492794e-01 5.40797751e-01 7.14717690

#Write a NumPy program to generate 8 random integers between 100 and 300

In [ ]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[134 216 210 115 132 223 207 287]


#Write a NumPy program to create a random integer nos of size 20 and sort it.

In [ ]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.67870257 0.28057401 0.45434785 0.07690504 0.41882743 0.20679312
 0.67061173 0.32961907 0.92515681 0.05864516 0.93180446 0.93209949
 0.41027758 0.72797953 0.67114593 0.22241217 0.62419273 0.25206894
 0.88291315 0.89701441]
Sorted array:
[0.05864516 0.07690504 0.20679312 0.22241217 0.25206894 0.28057401
 0.32961907 0.41027758 0.41882743 0.45434785 0.62419273 0.67061173
 0.67114593 0.67870257 0.72797953 0.88291315 0.89701441 0.92515681
 0.93180446 0.93209949]
